# ===================================
#  Form Behavior Config
# ===================================

name: Blog Category
form: /plugins/rainlab/blog/models/category/form_fields.yaml
model-class: Plugins\RainLab\Blog\Models\Category
default-redirect: rainlab/blog/categories

create:
    redirect: rainlab/blog/categories/update/:id
    redirect-close: rainlab/blog/categories

update:
    redirect: rainlab/blog/categories
    redirect-close: rainlab/blog/categories
