# ===================================
#  Form Behavior Config
# ===================================

name: Blog Category
form: /plugins/october/blog/models/category/form_fields.yaml
model-class: Plugins\October\Blog\Models\Category
default-redirect: october/blog/categories

create:
    redirect: october/blog/categories/update/:id
    redirect-close: october/blog/categories

update:
    redirect: october/blog/categories
    redirect-close: october/blog/categories
