# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: @/plugins/rainlab/blog/models/category/list_columns.yaml

# Model Class name
model-class: RainLab\Blog\Models\Category

# List Title
title: Manage Blog Categories

# Link URL for each record
record-url: rainlab/blog/categories/update/:id

# Message to display if the list is empty
no-records-message: backend::lang.list.no_records

# Records to display per page
records-per-page: 5

# Display checkboxes next to each record
show-checkboxes: no

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt



