# ===================================
#  Form Behavior Config
# ===================================

name: Blog Post
form: /plugins/rainlab/blog/models/post/form_fields.yaml
model-class: Plugins\RainLab\Blog\Models\Post
default-redirect: rainlab/blog/posts

create:
    redirect: rainlab/blog/posts/update/:id
    redirect-close: rainlab/blog/posts

update:
    redirect: rainlab/blog/posts
    redirect-close: rainlab/blog/posts
